# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables", "autolink"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Al's Ramblings
tagline:          'A UNIX Guy'
description:      'Automation, UNIX and other assorted random thoughts'
url:              http://www.resilvered.com
baseurl:          /

author:
  name:           'Alan Chalmers'
  url:            https://twitter.com/bigal

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/reslivered/resilvered.github.io
